# Generated by Django 5.0.1 on 2026-01-11 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
