# Generated by Django 5.0.1 on 2026-01-11 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0002_booking_status'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['user_id'], name='idx_booking_user_id'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status'], name='idx_booking_status'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['user_id', 'status'], name='idx_user_status_lookup'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['id', 'available_tickets'], name='idx_event_inventory'),
        ),
    ]
